allow jar for BAM joining to be specified on command line

diff --git a/bin/pb_align b/bin/pb_align
--- a/bin/pb_align
+++ b/bin/pb_align
@@ -25,8 +25,9 @@ initialise ()
     spatial_filter=""
     intensity_dir=""
     sf_parms=""
+    bam_join_jar="/software/solexa/bin/aligners/illumina2bam/current/BamMerger.jar"
 
-    TEMP=`getopt -a -o h --long bam:,read:,read1:,read2:,pf_filter,ref:,aln_parms:,spatial_filter,intensity_dir:,sf_parms:,prefix:,help -n $0 -- "$@"`
+    TEMP=`getopt -a -o h --long bam:,read:,read1:,read2:,pf_filter,ref:,aln_parms:,spatial_filter,intensity_dir:,sf_parms:,bam_join_jar:,prefix:,help -n $0 -- "$@"`
 
     if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
@@ -44,35 +45,38 @@ initialise ()
  	    --spatial_filter) spatial_filter=1; echo "will apply spatial_filter" >&2; shift 1 ;;
             --intensity_dir) intensity_dir=$2; echo "intensity_dir $intensity_dir" >&2; shift 2 ;;
 	    --sf_parms) sf_parms=$2; echo "sf_parms options $sf_parms" >&2; shift 2 ;;
+	    --bam_join_jar) bam_join_jar=$2; echo "bam_join_jar $bam_join_jar" >&2; shift 2 ;;
             --prefix) prefix=$2; echo "prefix $prefix" >&2; shift 2 ;;
             -h|--help) echo "Usage: $0 [options]";
                        echo "                   ";
-                       echo "       -bam <bam file>";
+                       echo "       --bam <bam file>";
                        echo "                   ";
-                       echo "       -read <read>        0-single-ended read in bam file, 1-first read in bam file, 2-second read in bam file";
+                       echo "       --read <read>        0-single-ended read in bam file, 1-first read in bam file, 2-second read in bam file";
                        echo "                             single read, no default";
-                       echo "       -read1 <read1>      1-first read in bam file, 2-second read in bam file";
-                       echo "       -read2 <read2>      1-first read in bam file, 2-second read in bam file";
+                       echo "       --read1 <read1>      1-first read in bam file, 2-second read in bam file";
+                       echo "       --read2 <read2>      1-first read in bam file, 2-second read in bam file";
                        echo "                             paired reads, no default";
                        echo "                   ";
-                       echo "       -pf_filter          purity filter reads";
+                       echo "       --pf_filter          purity filter reads";
                        echo "                             default do not purity filter reads";
                        echo "                   ";
                        echo "                   ";
-                       echo "       -ref <ref>          full path to reference";
+                       echo "       --ref <ref>          full path to reference";
                        echo "                   ";
-                       echo "       -aln_parms <bwa aln parameters>";
+                       echo "       --aln_parms <bwa aln parameters>";
                        echo "                             no default";
                        echo "                   ";
                        echo "                   ";
-                       echo "       -spatial_filter     apply spatial filtering to the bam files";
+                       echo "       --spatial_filter     apply spatial filtering to the bam files";
                        echo "                   ";
-                       echo "       -intensity_dir <raw intensity directory>";
+                       echo "       --intensity_dir <raw intensity directory>";
                        echo "                   ";
-                       echo "       -sf_parms <spatial_filter parameters>";
+                       echo "       --sf_parms <spatial_filter parameters>";
                        echo "                             no default";
                        echo "                   ";
-                       echo "       -prefix <prefix>    output file prefix";
+                       echo "       --bam_join_jar <bam join jar inc. full path>";
+                       echo "                   ";
+                       echo "       --prefix <prefix>    output file prefix";
                        echo "                             no default";
                        echo "                   ";
                        echo "       -h|--help   ";
@@ -112,17 +116,23 @@ initialise ()
         echo "You must supply a prefix" >&2
         exit 1
     fi
+
+    if [ ! -r $bam_join_jar ] ; then
+        echo "Cannot read bam join jar $bam_join_jar" >&2
+        exit 1
+    fi
 }
 
 set -o errexit
 set -o nounset
 
+initialise "$@"
+
 tools=$(dirname $0)
-tools=$(readlink -f $tools)
+tools=$(readlink -e $tools)
 bwa=$(which bwa)
 bwa=$(readlink -e $bwa)
-
-initialise "$@"
+bam_join_jar=$(readlink -e $bam_join_jar)
 
 if [ -z $ref ] ; then
   echo "You must specify the full path to the reference" >&2
@@ -139,7 +149,6 @@ fi
 output=${prefix}.bam
 echo "Making bam file $output" >&2
 
-picard_jar="/software/solexa/bin/aligners/illumina2bam/current/BamMerger.jar"
 if [ $read ] ; then
   picard_parms="VALIDATION_STRINGENCY=SILENT QUIET=true INPUT=$bam ALIGNED=/dev/stdin OUTPUT=$output"
 else
@@ -158,7 +167,7 @@ if [ $read ] ; then
 
     bwa samse $ref $sai $bam \
      | perl -aF'\t' -ne 'BEGIN{$filter=int(shift)} print unless ($F[1] & $filter || $F[1] & 4)' $filter \
-     | java -Xmx1024M -jar $picard_jar $picard_parms
+     | java -Xmx1024M -jar $bam_join_jar $picard_parms
 else
     sai1=${prefix}_1.sai
     bwa aln $aln_parms $ref -b1 $bam > $sai1
@@ -168,7 +177,7 @@ else
 
     bwa sampe $ref $sai1 $sai2 $bam $bam \
      | perl -aF'\t' -ne 'BEGIN{$filter=int(shift)} print unless ($F[1] & $filter || ($F[1] & 4 && $F[1] & 8))' $filter \
-     | java -Xmx1024M -jar $picard_jar $picard_parms | samtools fixmate - $output
+     | java -Xmx1024M -jar $bam_join_jar $picard_parms | samtools fixmate - $output
 fi
 
 if [ ! -s $output ] ; then
