pb_align: check flagstats before AND after spatial_filter, fix for single-ended bam files, tidied code tag pb_calibration: when checking for paired-end bam files include QC failed predictor_pu.c: force N's to have quality 0 and set min quality for non N's to 1 cd bcl file where N <=> quality 0 parse_bam.c: update alignment parsing to handle indels at start/end of aligmnet and ambiguity codes in MD tag

diff --git a/bin/pb_align b/bin/pb_align
--- a/bin/pb_align
+++ b/bin/pb_align
@@ -49,7 +49,7 @@ initialise ()
                        echo "                   ";
                        echo "       -bam <bam file>";
                        echo "                   ";
-                       echo "       -read <read>        1-first read in bam file, 2-second read in bam file";
+                       echo "       -read <read>        0-single-ended read in bam file, 1-first read in bam file, 2-second read in bam file";
                        echo "                             single read, no default";
                        echo "       -read1 <read1>      1-first read in bam file, 2-second read in bam file";
                        echo "       -read2 <read2>      1-first read in bam file, 2-second read in bam file";
@@ -152,46 +152,19 @@ fi
 
 if [ $read ] ; then
     sai=${prefix}.sai
-    if [ $bam ] ; then
-        fastq_files="-b${read} $bam"
-    else
-        fastq_files=$fastq
-    fi
-    bwa aln $aln_parms $ref $fastq_files > $sai
+    bwa aln $aln_parms $ref -b${read} $bam > $sai
 
-    sai_files=$sai
-    if [  $bam ] ; then
-        fastq_files=$bam
-     else
-        fastq_files=$fastq
-    fi
-    bwa samse $ref $sai_files $fastq_files \
+    bwa samse $ref $sai $bam \
      | perl -aF'\t' -ne 'BEGIN{$filter=int(shift)} print unless ($F[1] & $filter || $F[1] & 4)' $filter \
      | java -Xmx1024M -jar $picard_jar $picard_parms
 else
     sai1=${prefix}_1.sai
-    if [ $bam ] ; then
-        fastq_files="-b1 $bam"
-    else
-        fastq_files=$fastq1
-    fi
-    bwa aln $aln_parms $ref $fastq_files > $sai1
+    bwa aln $aln_parms $ref -b1 $bam > $sai1
 
     sai2=${prefix}_2.sai
-    if [ $bam ] ; then
-        fastq_files="-b2 $bam"
-    else
-        fastq_files=$fastq2
-    fi
-    bwa aln $aln_parms $ref $fastq_files > $sai2
+    bwa aln $aln_parms $ref -b2 $bam > $sai2
 
-    sai_files="$sai1 $sai2"
-    if [ $bam ] ; then
-        fastq_files="$bam $bam"
-    else
-        fastq_files="$fastq1 $fastq2"
-    fi
-    bwa sampe $ref $sai_files $fastq_files \
+    bwa sampe $ref $sai1 $sai2 $bam $bam \
      | perl -aF'\t' -ne 'BEGIN{$filter=int(shift)} print unless ($F[1] & $filter || ($F[1] & 4 && $F[1] & 8))' $filter \
      | java -Xmx1024M -jar $picard_jar $picard_parms | samtools fixmate - $output
 fi
@@ -200,6 +173,30 @@ if [ ! -s $output ] ; then
     echo "failed to create output file $output" >&2
     exit 1
 fi
+
+stat_file=${prefix}_flagstat.txt
+samtools flagstat $output > $stat_file
+if [ ! -s $stat_file ] ; then
+    echo "failed to create flagstat file" >&2
+    exit 1
+fi
+
+pair=`awk '/[0-9]+ paired in sequencing/ {print $1+$3}' $stat_file`
+if [ $pair -gt 0 ] ; then
+    count=`awk '/[0-9]+ properly paired/ {print $1}' $stat_file`
+    if [ $count -lt 200000 ] ; then
+        echo "Only $count properly paired reads < 200000" >&2
+        exit 0
+    fi
+else
+    count=`awk '/[0-9]+ mapped/ {print $1}' $stat_file`
+    if [ $count -lt 100000 ] ; then
+        echo "Only $count reads align < 100000" >&2
+        exit 0
+    fi
+fi
+
+echo "Making spatial filter..." >&2
 
 #
 # Spatial Filter options
@@ -222,7 +219,6 @@ fi
 
 stat_file=${prefix}_flagstat.txt
 samtools flagstat $output > $stat_file
-
 if [ ! -s $stat_file ] ; then
     echo "failed to create flagstat file" >&2
     exit 1
